[package]
name = "dwui"
version = "0.9.1"
edition = "2021"
description = "UI Component library built on the DWIND style crate!"
homepage = "https://github.com/JedimEmO/dwind"
repository = "https://github.com/JedimEmO/dwind"
license = "MIT"
keywords = ["web", "wasm", "css", "style"]

[dependencies]
const_format = { workspace = true }
dominator = { workspace = true }
dwind = { path = "../dwind", version = "0.8.0" }
dwind-macros = { path = "../dwind-macros", version = "0.5.0" }
futures-signals = { workspace = true }
futures-signals-component-macro = { workspace = true }
once_cell = { workspace = true }
web-sys = { workspace = true }

[dev-dependencies]
futures = { workspace = true }
wasm-bindgen-futures = { workspace = true }
wasm-bindgen-test = { workspace = true }
web-sys = { workspace = true, features = [
    "CssKeyframesRule",
    "CssRule",
    "CssRuleList",
    "CssStyleDeclaration",
    "CssStyleRule",
    "CssStyleSheet",
    "Document",
    "HtmlElement",
    "HtmlInputElement",
    "KeyboardEvent",
    "KeyboardEventInit",
    "NodeList",
    "StyleSheet",
    "StyleSheetList",
    "console",
] }

[build-dependencies]
dominator-css-bindgen = { path = "../dominator-css-bindgen", version = "0.2.0" }
serde = { workspace = true }
