[package]
name = "example-html-highlight-macro"
version = "0.1.1"
edition = "2021"
description = "macro for embedding syntax highlighted copies of code in the binary"
homepage = "https://github.com/JedimEmO/dwind"
repository = "https://github.com/JedimEmO/dwind"
license = "MIT"
keywords = ["web", "wasm", "css", "style"]

[lib]
proc-macro = true

[dependencies]
prettyplease = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
syntect = { workspace = true }
